
# all paths are relative to the xGIS folder (considered root). This is the expected folder structure
# [root_dir]           YOURPROJECT
#                      |-- toolbox.pyt                    <--- ArcGIS toolbox file
#                      |-- qgis_toolbox.py                <--- QGIS toolbox file
#                      |-- qgis_interface.ui              <--- QGIS toolbox interface
#                      |-- ...
#                      |-- python_module                  <--- your module
#                          |-- file_one.py
#                          `-- file_two.py
#                      |--  xgis
#                          |-- core                           <--- This is xGIS
#                              |-- __init__.py
#                              |-- _version.py
#                              |-- executor.py
#                              `-- log_utils.py
# [runtime_dir]            |-- build_utils
#                              |-- Build_installer.py
#                              |-- config_template.txt
#                              |-- build_config.yaml
#                              |-- 7zsd_All_x64.sfx
#                              |-- setup.bat
# [build_dir ]                 `-- Build
#                                  |-- xGIS                  <--- This is how your toolbox will look like once installed
# [target_dir]                     |   `-- TOOLBOX_NAME
#                                  |-- config.txt            <--- This is the automatically generated config file for the self-extracting archive
#                                  `-- Installer.exe         <--- This is your installer generated after running Build_installer.py
#                          |-- scripts
#                              |-- getpip.py
#                              `-- setup_external_libs.py
#                          |-- wheels
#                              |-- python_module.whl


# Installation process
# the installation process will go through 2 steps that can be controlled using the respective build parameters and scripts associated with them
# 1. Extracting files
#    you can control various operations using the config.txt. This is automatically generated using the config_template.txt and various build_config.yaml parameters
# 2. Running a post extraction script/program [use the installer_script parameter]
#    The default one is tailored to perform the module installation using the setup_external_libs.py script and a requirements.yaml file
# 2a. If using the default setup.bat, open a splash screen [use the splash_screen parameter]

# Additional customisation
# First level: you can modify the config_template.txt to add extra parameters to the 7zsd self-extracting exe. 
#              Those will be maintained in the config.txt generated by the build process
# Second level: you can control the post extraction step by providing a custom setup.bat or exe to run


# General info
name: xGIS
version: 0.1

# Package build options
build_folder: # ['', path/relative/to/root] # path to use for the build (temporary files)
installer_script: setup.bat # ['', path/relative/to/root, 'setup.bat'] # script to run after the extraction. if None the post extraction task will be skipped

# setup.bat options
ArcGIS_support: True # [True, False]
QGIS_support: False # [True, False]
# option to embed a python version with the toolbox, please see https://docs.python.org/3.5/using/windows.html#embedded-distribution
# IMPORTANT installing libraries that require compiling/building wheels may not be supported as embeddable Python do not come with Python.h and other resources to include at compilation
# in that case it is reccomended that you provide precompiled wheels to setup_external_libs.py (for example from https://www.lfd.uci.edu/~gohlke/pythonlibs/
Python_embedded: xgis/python-3.8.10-embed-amd64.zip #['', path/relative/to/root/.zip]
Python_version: 3  # ['', 2, 3] # for backend scripts
splash_screen: '' # ['', path/relative/to/root/.html] # If specified will open the given html upon successful installation

# Folders (and files) to include.
include_data: # list of files and folders to include
  # default values for most projects
  .: # to include the entire root folder
  xgis:
    core: # to include specific files in a folder
      - __init__.py
      - _version.py
      - executor.py
      - log_utils.py
      - arctoolbox.py
    scripts:
    wheels:
      - "*.whl"
  # here add you additional packages

# Folders (and files) to exclude. If the folder in not in include_data it will not have effect
exclude_data:
  # default values for most projects
  .:
    - .gitignore
    - .gitmodules
    - "*.pyc"
    - "*.zip" # if we have an embedded python zip file, this will be handled separately
  # here add your files to exclude

# folders to be remapped. Paths are relative to the root folder. If the folder is not in include_data it will not have effect
remap_folders:
  # default values for most projects
  xgis:
    core: xgis\
    scripts: .\
    wheels: .\
  # here add your folders to remap
